### ISSUE TITLE
Can't access node-inspector via Vagrant VM

### ISSUE THREAD

**Issue by gplusdotgr** [node-inspector/node-inspector#460]
I have a Vagrant VM (created with puphpet). This is my node-inspector grunt task config:

```
        'node-inspector': {
            custom: {
                options: {
                    'web-port': 9500,
                    'web-host': 'localhost',
                    'debug-port': 5858,
                    'save-live-edit': true,
                    'no-preload': true,
                    'stack-trace-limit': 50,
                    'hidden': []
                }
            }
        },
```

I start Grunt, I get: 

```
debugger listening on port 5858

 NODE_ENV is not defined! Using default development environment

Node Inspector v0.7.4
Visit http://localhost:9500/debug?port=5858 to start debugging.
```

But when I try to either curl or visit my domain with this port parameters, I get connection refused.

```
gplus@g-on-mac:~/vm$ curl 'http://www.demoapp.dev:9500/debug?5858'
curl: (7) Failed to connect to www.demoapp.dev port 9500: Connection refused
```

Here's my VM port-forwarding setup:

```
        network:
            private_network: 192.168.56.102
            forwarded_port:
                VNbBU1aiFEBb:
                    host: '9501'
                    guest: '22'
                FBcBU2aiCFFe:
                    host: '3000'
                    guest: '3000'
                GVdCU5ahSCMf:
                    host: '9500'
                    guest: '9500'
```

The normal mode works:

```
/vm$ curl 'http://www.demoapp.dev:3000' -v
* Rebuilt URL to: http://www.demoapp.dev:3000/
* Hostname was NOT found in DNS cache
*   Trying 192.168.56.102...
* Connected to www.demoapp.dev (192.168.56.102) port 3000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.demoapp.dev:3000
> Accept: */*
> 
< HTTP/1.1 200 OK

...

```
